config/routes.rb
Rails.application.routes.draw do

  namespace :finance do
    root 'application#index'
    resources :estimates, only: [:index]
    resources :invoices, only: [:index]
    resources :retainer_invoices, only: [:index]
    resources :purchase_orders, only: [:index]
    resources :unbillable_purchase_orders, only: [:index]
  end

  namespace :admin do
    root 'application#index'
    resources :clients, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :ventypes do
      resources :vendors
    end
  end

  devise_for :users
  root 'clients#index'
  
  resources :clients, only: [:index, :show, :edit, :update] do
    resources :billable_entities
    resources :unbillable_purchase_orders, except: [:index]
    resources :retainer_invoices, except: [:index]
    resources :jobs do
      collection do
        get :search
      end
      member do
        post :watch
      end
      resources :estimates, except: [:index]
    end
  end
  
  resources :estimates, only: [] do
    resources :invoices, except: [:index]
    resources :invoice_requisitions
    resources :purchase_orders, except: [:index]
  end
  
  resources :jobs, only: [] do
    resources :comments, only: [:create]
    resources :estimate_requisitions
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
  
  resources :wassups
  resources :holidays
  resources :leave_applications
  
  
  resources :attachments, only: [:show, :new, :destroy]
  resources :images, only: [:show, :new, :destroy]
  resources :ideas, only: [:show, :new, :destroy]
  resources :estfiles, only: [:show, :new, :destroy]
end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  belongs_to :job
  belongs_to :vendor
  belongs_to :billable_entity
  belongs_to :author, class_name: "User"
  
  has_many :invoices, dependent: :destroy
  has_many :invoice_requisitions, dependent: :destroy
  has_many :purchase_orders, dependent: :destroy
  has_many :estfiles, dependent: :destroy
  accepts_nested_attributes_for :estfiles, reject_if: :all_blank
  
  validates :name, presence: true
  validates :description, presence: true
  
  before_create :set_serial_number
  after_create :set_final
  
  before_update :set_final_update, :if => :estimate_type_changed?
  
  def set_serial_number
    self.serial_number = "/#{created_at.month}/#{created_at.year}/"
  end
  
  def set_final
    num = "#{id}"
    num = num.to_i + 992
    self.serial_number = "#{estimate_type}" + self.serial_number + "#{num}"
    self.save
  end
  
  def set_final_update
    num = "#{id}"
    num = num.to_i + 992
    self.serial_number = "#{estimate_type}/#{created_at.month}/#{created_at.year}/#{num}"
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_client_job
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]
  
  def new
    @estimate = @job.estimates.build
    authorize @estimate, :create?
    @estimate.estfiles.build
  end
  
  def create
    @estimate = @job.estimates.build(estimate_params)
    @estimate.author = current_user
    authorize @estimate, :create?
    
    if @estimate.save
      flash[:notice] = "Estimate has been created"
      redirect_to [@client, @job, @estimate]
    else
      flash.now[:alert] = "Estimate was not created"
      render "new"
    end
  end
  
  def show  
    vendor = @estimate.vendor
    authorize @estimate, :show?
    
    respond_to do |format|
      format.html
      format.pdf do
        pdf = EstimatePdf.new(@estimate, view_context)
        send_data pdf.render, filename: "estimate_#{@estimate.created_at.strftime("%d/%m/%Y")}.pdf", type: "application/pdf"
      end
    end
  end
  
  def edit
    authorize @estimate, :update?
    @estimate.estfiles.build
  end
  
  def update
    authorize @estimate, :update?
    
    if @estimate.update(estimate_params)
      flash[:notice] = "Estimate was updated"
      redirect_to [@client, @job, @estimate]
    else
      flash.now[:alert] = "Estimate was not updated"
      render "edit"
    end
  end
  
  def destroy
    authorize @estimate, :destroy?
    
    @estimate.destroy
    flash[:notice] = "Estimate was deleted"
    redirect_to [@client, @job]
  end
  
  private
  
  def estimate_params
    params.require(:estimate).permit(:name, :description, :job_id, :client_id, :billable_entity_id, :vendor_id, :printer_date, :printer_title, :amount, :estimate_type, :notes, :signoff, :signatory, :status, :client_signatory, estfiles_attributes: [:file, :file_cache])
  end
  
  def set_client_job
    @client = Client.find(params[:client_id])
    @job = Job.find(params[:job_id])
  end
  
  def set_estimate
    @estimate = @job.estimates.find(params[:id])
  end
end

app/controllers/finance/estimates_controller.rb
class Finance::EstimatesController < Finance::ApplicationController
  
  def index
    @estimates = Estimate.paginate(:page => params[:page], :per_page => 25).order("created_at desc")
  end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/finance/estimates_helper.rb
module Finance::EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= simple_form_for([client, job, estimate]) do |f| %>
<%= f.label :estimate_type %><br>
<%= f.select :estimate_type, ['ART', 'AV', 'PRD', 'PRJ', 'WEB', 'MIS'], :selected => f.object.estimate_type %><br><br>
<%= f.label :status %><br>
<%= f.select :status, ['Unapproved', 'Partly Invoiced', 'Fully Invoiced', 'Closed'], :selected => f.object.status %><br><br>

<%= f.label :billable_entity_id %><br>
<%= f.collection_select :billable_entity_id, client.billable_entities.order(:name), :id, :name, :selected => f.object.billable_entity_id %><br><br>
 
 <div id="estfiles" >
   <h3>Attachments</h3>
   <%= render partial: "estfiles/form", locals: { f: f, index: 0 } %>
 </div>
 <p>
   <%= link_to "Add another file", new_estfile_path, remote: true, id: "add_file", data: { params: {index: estimate.estfiles.size} } %>
 </p>
  
<%= f.input :name %>
<%= f.input :description %>
<%= f.input :amount %>
 
<%= f.label :vendor_id %><br>
<%= f.collection_select :vendor_id, Vendor.order(:name), :id, :name, :selected => f.object.vendor_id || 1 %><br><br>
 
<%= f.input :notes, :input_html => { :value => 'This is an estimate of costs. Not a firm quotation. Rates are subject to change. Queries relating to this estimate if any must be brought to our notice in writing within 10 days of receipt, failing which the estimate will be deemed to be correct. Please note if you receive this Estimate as a computer-generated PDF document no signature is required. Taxes as applicable will be charged extra.'} %>
 
<%= f.input :signoff, :input_html => { :value => 'For METAL Communications Pvt Ltd' } %>
  
<%= f.input :signatory, :input_html => { :value => 'Production & Studio' } %>
 
<%= f.input :client_signatory, :input_html => { :value => 'Authorised Signatory for Client: _______________________ dated ______________' } %><br>
  
<%= f.input :printer_title, :input_html => { :value => 'E S T I M A T E' } %>
<%= f.input :printer_date %><br>
  
  
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/estimates/edit.html.erb
<header>
  <h4>Edit Estimate <small><%= @job.name %></small></h4>
</header>

<%= render "form", client: @client, job: @job, estimate: @estimate %>

app/views/estimates/new.html.erb
<header>
  <h2>New Estimate <small><%= @job.name %></small></h2>
</header>

<%= render "form", client: @client, job: @job, estimate: @estimate %>

app/views/estimates/show.html.erb
<div id="estimate">
  <header>
    <h4>Job <small><%= link_to @job.name, [@client, @job] %></small></h4>
  </header>
  
  <header>
    <h4 class="headercolor">Estimate <small class="smallcolor"><%= @estimate.name %></small></h4>
    
    <ul class="actions">
      <li>
        <%= link_to "PDF", client_job_estimate_path(@client, @job, @estimate, :format => "pdf"), class: "pdf" %>
      </li>
      <li>
        <a href="#" class="print" onclick="window.print();return false;">Print </a>
      </li>
      <% if policy(@estimate).update? %>
      <li>
        <%= link_to "Edit Estimate", [:edit, @client, @job, @estimate], class: "edit" %>
      </li>
      <% end %>
      <% if policy(@estimate).destroy? %>
      <li>
        <%= link_to "Delete Estimate", [@client, @job, @estimate], method: :delete, data: { confirm: "Are you sure you want to delete this estimate?" }, class: "delete" %>
      </li>
      <% end %>
    </ul>
  </header> 
  
  <table id="attributes">
    <tr>
      <th>Author:</th>
      <td><%= @estimate.author.email %></td>
    </tr>
    
    <tr>
      <th>Created:</th>
      <td><%= time_ago_in_words(@estimate.created_at) %> ago</td>
    </tr>
    
    <tr>
      <th>Job reference#:</th>
      <td><%= link_to @job.serial_number, [@client, @job] %></td>
    </tr>
    
    <tr>
      <th>Estimate#:</th>
      <td><%= @estimate.serial_number %></td>
    </tr>
    
    <tr>
      <th>Title:</th>
      <td><%= @estimate.name %></td>
    </tr>
    
    <tr>
      <th>Vendor:</th>
      <td><%= @estimate.vendor.name if !@estimate.vendor.nil? %></td>
    </tr>
    
    <% if @estimate.estfiles.any? %>
      <tr class="estfiles">
        <th>Attachments:</th>
        <td><% @estimate.estfiles.each do |estfile| %>
          <p>
            <%= link_to File.basename(estfile.file.url), estfile_path(estfile) %>
            (<%= number_to_human_size(estfile.file.size) %>)

            <% if policy(estfile).destroy? %>
            <%= link_to "Delete Attachment", estfile_path(estfile), method: :delete, data: { confirm: "Are you sure you want to delete this Attachment?" } %></p>     
          <% end %>
        <% end %></td>
      </tr>
      
      <tr>
      <th>Status:</th>
      <td><strong><%= @estimate.status %></strong></td>
    </tr>
      
    <% end %>
  </table>   
  
  <div id="printer">
  <p class="logo"><%= image_tag 'METAL-LOGO.jpg' %><small class="address">#3, Sarkar Heritage, Kane Road, Bandstand, Bandra West, Mumbai 400 050. Tel: 91 22 6170 2600</small></p>
  <h3><%= @estimate.printer_title %></h3><br />
    <p><%= l @estimate.printer_date if @estimate.printer_date %></p>
  <p>Estimate#: <%= @estimate.serial_number %></p><br />
  <h4>Client: <%= @estimate.job.client.name %></h4> 
  <p><%= @estimate.billable_entity.name %></p>
  <p><%= simple_format(@estimate.billable_entity.address) %></p><br />
  
  <p><strong><%= @estimate.name %></strong></p>
   
  <p><%= simple_format(@estimate.description) %></p>
  <p>INR <%= number_with_delimiter(@estimate.amount) %></p><br />
  
  <p><small><%= simple_format(@estimate.notes) %></small></p>
  <p><%= @estimate.signoff %></p><br /><br />
  <p><%= @estimate.signatory %></p>
  <p><%= @estimate.client_signatory %></p>
  </div>
  
  <header>
  <h5>Invoice Requisitions</h5>
  
  <ul class="actions">
    <% if policy(InvoiceRequisition.new(estimate: @estimate)).create? %>
    <li><%= link_to "New Invoice requisition", new_estimate_invoice_requisition_path(:estimate_id => (params[:id])), class: "new" %></li>
    <% end %>
  </ul>
</header>
  
  <ul id="invoice_requisitions">
    <% @estimate.invoice_requisitions.each do |invoice_requisition| %>
  <li>
    #<%= invoice_requisition.id %> - <%= link_to invoice_requisition.notes, [@estimate, invoice_requisition] %>
  </li>
  <% end %>
</ul>
 
 <header>
  <h5>Purchase Orders</h5>
  
  <ul class="actions">
    <% if policy(PurchaseOrder.new(estimate: @estimate)).create? %>
    <li><%= link_to "New Purchase Order", new_estimate_purchase_order_path(:estimate_id => (params[:id])), class: "new" %></li>
    <% end %>
  </ul>
</header>
 
 <ul id="purchase_orders">
  <% @estimate.purchase_orders.each do |purchase_order| %>
  <li>
    #<%= purchase_order.id %> - <%= link_to purchase_order.title, [@estimate, purchase_order] %>
  </li>
  <% end %>
</ul>

 <header>
  <h5>Invoices</h5>
  
  <ul class="actions">
    <% if policy(Invoice.new(estimate: @estimate)).create? %>
    <li><%= link_to "New Invoice", new_estimate_invoice_path(:estimate_id => (params[:id])), class: "new" %></li>
    <% end %>
  </ul>
</header>

<ul id="invoices">
  <% @estimate.invoices.each do |invoice| %>
  <li>
    #<%= invoice.id %> - <%= link_to invoice.title, [@estimate, invoice] %>
  </li>
  <% end %>
</ul>