config/routes.rb
Rails.application.routes.draw do

  namespace :finance do
    root 'application#index'
    resources :estimates, only: [:index]
    resources :invoices, only: [:index]
    resources :retainer_invoices, only: [:index]
    resources :purchase_orders, only: [:index]
    resources :unbillable_purchase_orders, only: [:index]
  end

  namespace :admin do
    root 'application#index'
    resources :clients, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :ventypes do
      resources :vendors
    end
  end

  devise_for :users
  root 'clients#index'
  
  resources :clients, only: [:index, :show, :edit, :update] do
    resources :billable_entities
    resources :unbillable_purchase_orders, except: [:index]
    resources :retainer_invoices, except: [:index]
    resources :jobs do
      collection do
        get :search
      end
      member do
        post :watch
      end
      resources :estimates, except: [:index]
    end
  end
  
  resources :estimates, only: [] do
    resources :invoices, except: [:index]
    resources :invoice_requisitions
    resources :purchase_orders, except: [:index]
  end
  
  resources :jobs, only: [] do
    resources :comments, only: [:create]
    resources :estimate_requisitions
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
  
  resources :wassups
  resources :holidays
  resources :leave_applications
  
  
  resources :attachments, only: [:show, :new, :destroy]
  resources :images, only: [:show, :new, :destroy]
  resources :ideas, only: [:show, :new, :destroy]
  resources :estfiles, only: [:show, :new, :destroy]
end

app/models/billable_entity.rb
class BillableEntity < ActiveRecord::Base
  belongs_to :client
  has_many :retainer_invoices
  has_many :estimates
  has_many :invoices
  
  validates :name, presence: true
end

app/controllers/billable_entities_controller.rb
class BillableEntitiesController < ApplicationController
  before_action :set_client
  before_action :set_billable_entity, only: [:show, :edit, :update, :destroy]
  
  def new
    @billable_entity = @client.billable_entities.build
    authorize @billable_entity, :create?
  end
  
  def create
    @billable_entity = @client.billable_entities.build(billable_entity_params)
    authorize @billable_entity, :create?
    
    if @billable_entity.save
      flash[:notice] = "Billable entity has been created"
      redirect_to [@client, @billable_entity]
    else
      flash.now[:alert] = "Billable entity was not created"
      render "new"
    end
  end
  
  def show
    authorize @billable_entity, :show?
  end
  
  def edit
    authorize @billable_entity, :update?
  end
  
  def update
    authorize @billable_entity, :update?
    
    if @billable_entity.update(billable_entity_params)
      flash[:notice] = "Billable entity was updated"
      redirect_to [@client, @billable_entity]
    else
      flash.now[:alert] = "Billable entity was not updated"
      render "edit"
    end
  end
  
  def destroy
    authorize @billable_entity, :destroy?
    
    @billable_entity.destroy
    flash[:notice] = "Billable entity was deleted"
    
    redirect_to @client
  end
  
  private
  
  def set_client
    @client = Client.find(params[:client_id])
  end
  
  def set_billable_entity
    @billable_entity = @client.billable_entities.find(params[:id])
  end
  
  def billable_entity_params
    params.require(:billable_entity).permit(:name, :phone, :contact_name, :email, :address)
  end
end

app/helpers/billable_entities_helper.rb
module BillableEntitiesHelper
end

app/views/billable_entities/_form.html.erb
<%= simple_form_for([client, billable_entity]) do |f| %>
  <%= f.input :name %>
  <%= f.input :contact_name %>
  <%= f.input :address %>
  <%= f.input :email %>
  <%= f.input :phone %>
  
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/billable_entities/edit.html.erb
<header>
  <h2>Edit Billable entity <small><%= @client.name %></small></h2>
</header>

<%= render "form", client: @client, billable_entity: @billable_entity %>

app/views/billable_entities/new.html.erb
<header>
  <h2>New Billable entity <small><%= @client.name %></small></h2>
</header>

<%= render "form", client: @client, billable_entity: @billable_entity %>

app/views/billable_entities/show.html.erb
<div id="billable_entities">
  <header>
    <h4>Client <small><%= link_to @client.name, client_path(@client) %></small></h4>
  </header>
  
  <header>
    <h4 class="headercolor">Billable entity <small class="smallcolor"><%= @billable_entity.name %></small></h4>
    
    <ul class="actions">
      <% if policy(@billable_entity).update? %>
      <li><%= link_to "Edit Billable entity", edit_client_billable_entity_path(@client, @billable_entity), class: "edit" %></li>
      <% end %>
      <% if policy(@billable_entity).destroy? %>
      <li><%= link_to "Delete Billable entity", client_billable_entity_path(@client, @billable_entity), method: :delete, data: { confirm: "Are you sure you want to delete this billable entity?" }, class: "delete" %></li>
      <% end %>
    </ul>
    
  </header>
  <p><%= @billable_entity.name %></p>
  <p><%= @billable_entity.contact_name %></p> 
  <p><%= simple_format(@billable_entity.address) %></p>
  <p><strong>Phone: </strong><%= @billable_entity.phone %></p>
  <p><strong>Email: </strong><%= @billable_entity.email %></p> 
  
</div>